/** Major Indian cities with their states — used for checkout location. */
export interface IndiaCity {
  city: string;
  state: string;
}

export const INDIA_CITIES: IndiaCity[] = [
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Allahabad", state: "Uttar Pradesh" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Bangalore", state: "Karnataka" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Delhi", state: "Delhi" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Goa", state: "Goa" },
  { city: "Gurgaon", state: "Haryana" },
  { city: "Guwahati", state: "Assam" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Hubli", state: "Karnataka" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Jammu", state: "Jammu and Kashmir" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Kochi", state: "Kerala" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Mysore", state: "Karnataka" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Patna", state: "Bihar" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Srinagar", state: "Jammu and Kashmir" },
  { city: "Surat", state: "Gujarat" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Warangal", state: "Telangana" },
].sort((a, b) => a.city.localeCompare(b.city));

export function stateForCity(city: string): string {
  return INDIA_CITIES.find((entry) => entry.city === city)?.state ?? "";
}
